# Enable or disable the plugin
category_private_writer_enabled:
  default: true
  client: true

# Categories that are private-writer style (comma-separated category IDs)
category_private_writer_categories:
  default: ''
  client: true

# Groups that have writer permissions (comma-separated group IDs)
category_private_writer_writer_groups:
  default: ''
  client: true

# Groups that have admin permissions (comma-separated group IDs)
category_private_writer_admin_groups:
  default: ''
  client: true