category_private_writer_enabled:
  default: false
  client: true
  description: "Enable private writer mode for specific categories"

category_private_writer_json:
  default: "[]"
  type: json
  client: true
  description: |
    JSON array of configurations for each category.
    
    Each entry format:
    {
      "category_id": <category_id>,
      "writer_groups": ["group1", "group2"],
      "admin_groups": ["group3", "group4"]
    }

    Example:
    [
      {
        "category_id": 1,
        "writer_groups": ["writers", "authors"],
        "admin_groups": ["category_admins"]
      },
      {
        "category_id": 2,
        "writer_groups": ["students"],
        "admin_groups": ["teachers", "mentors"]
      }
    ]
